---
title: "Owner Analysis"
Author: Angie Kochkarova
format: html
editor: visual
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}

lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
```

```{r}
glimpse(lobster_abundance)
summary(lobster_abundance)
names(lobster_abundance)
unique(lobster_abundance$SITE)
unique(lobster_abundance$SIZE_MM)
```

```{r}
lobster_abundance <- lobster_abundance %>%
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))
unique(lobster_abundance$SIZE_MM)
```

```{r}
no_napl <- lobster_abundance %>%
  filter(SITE != "NAPL")
unique(no_napl$SITE)
```

```{r}
aque_large <- lobster_abundance %>%
  filter(SITE == "AQUE", SIZE_MM > 70)
summary(aque_large$SIZE_MM)
unique(aque_large$SITE)
```

```{r}
max_size <- lobster_abundance %>%
  group_by(SITE, MONTH) %>%
  summarise(max_size = max(SIZE_MM, na.rm = TRUE), .groups = "drop")
```

## Exercise: Data Visualization

```{r}
## Run this chunk to test exercises ##

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)

lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv") %>%
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))
```

```{r}
hist_plot <- ggplot(lobster_abundance, aes(x = SIZE_MM)) +
  geom_histogram(binwidth = 5) +
  facet_wrap(~ SITE) +
  labs(title = "Distribution of Lobster Sizes by Site")

hist_plot
```

```{r}
lobster_yearly <- lobster_abundance %>%
  group_by(YEAR, SITE) %>%
  summarise(total_lobsters = sum(COUNT, na.rm = TRUE), .groups = "drop")

line_plot <- ggplot(lobster_yearly, aes(x = YEAR, y = total_lobsters, color = SITE)) +
  geom_line()

print(line_plot)
```

```{r}
lobster_size <- lobster_abundance %>%
  filter(YEAR %in% c(2019, 2020, 2021)) %>%
  mutate(size_category = ifelse(SIZE_MM < 70, "Small", "Large"))

lobster_counts <- lobster_size %>%
  group_by(SITE, size_category) %>%
  summarise(count = sum(COUNT, na.rm = TRUE), .groups = "drop")

bar_plot <- ggplot(lobster_counts, aes(x = SITE, y = count, fill = size_category)) +
  geom_col(position = "dodge")

print(bar_plot)
```

```{r}
pretty_line_plot <- ggplot(lobster_yearly, aes(x = YEAR, y = total_lobsters, color = SITE)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Total Lobsters Observed by Year",
    x = "Year",
    y = "Number of Lobsters",
    color = "Site"
  ) +
 scale_x_continuous(breaks = seq(2000, 2022, by = 2)) +
  scale_color_brewer(palette = "Set1") +
  theme_light() +
  theme(
    text = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 14),
    panel.grid.major = element_line(linetype = "dotted"),
    panel.background = element_rect(fill = "white")
  )
  print(pretty_line_plot)
```

```{r}
library(ggplot2)
ggsave(
  filename = "figs/lobster_line_plot.png",
  plot = pretty_line_plot,
  width = 8,
  height = 5
)
```

```{r}
list.files("figs")

```
```{r}
lobster_mpa <- lobster_abundance %>% 
  mutate(DESIGNATION = case_when(
    SITE %in% c("IVEE", "NAPL") ~ "MPA",
    TRUE ~ "not MPA"
  ))
head(lobster_mpa)
```

